[package]
name = "zoro"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-plonk = { version = "0.10.0", optional = true }
dusk-jubjub = { version = "0.11.1", optional = true }
dusk-bytes = { version = "0.1.5", optional = true }

bellman = { version = "0.13.0", optional = true }
bls12_381 = { version = "0.7.0", optional = true }

rand = "0.8.5"
rand_core = "0.6.3"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-integer = "0.1"
zeekit = {version="0.7.0", features=["groth16"]}
ff = { version = "0.12", features = ["derive", "derive_bits"] }

[features]
default = ["groth16"]
groth16 = ["bellman", "bls12_381"]
plonk = ["dusk-plonk", "dusk-jubjub", "dusk-bytes"]
